name: ASAP Computers
favicon: null
layout_spectrum: 0.6655820282176137
typography_spectrum: 0.5228884071111679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8570688997860998
  lightness: 0.8574756542220712
  saturation: 0.3775453062262386
  rhythmicContrast: 0.15515439119189978
purpose: []
